export const REVIEW_ALL_REQUEST = 'REVIEW_ALL_REQUEST'
export const REVIEW_ALL_SUCCESS = 'REVIEW_ALL_SUCCESS'
export const REVIEW_ALL_FAIL = 'REVIEW_ALL_FAIL'

export const REVIEW_MY_REQUEST = 'REVIEW_MY_REQUEST'
export const REVIEW_MY_SUCCESS = 'REVIEW_MY_SUCCESS'
export const REVIEW_MY_FAIL = 'REVIEW_MY_FAIL'
